# API URL of the cluster running the target clusterpool, used in oc login, so port :6443 is required
CLUSTERPOOL_HOST_API ?=

# Access credentials used to log in to cluster indciated in CLUSTERPOOL_HOST_API
CLUSTERPOOL_HOST_USER ?=
CLUSTERPOOL_HOST_PASS ?=

# Namespace where Hive ClusterPool resources reside
CLUSTERPOOL_HOST_NAMESPACE ?= clusterpool

# Namespace where the Hive pods reside on the cluster indciated in CLUSTERPOOL_HOST_API, usually "hive"
CLUSTERPOOL_HIVE_NAMESPACE ?= hive


.PHONY: clusterpool/create-image-set
clusterpool/create-image-set:
	echo unimplemented
	exit 1

.PHONY: clusterpool/delete-image-set
clusterpool/delete-image-set:
	echo unimplemented
	exit 1

.PHONY: clusterpool/create-cluster-pool
clusterpool/create-cluster-pool:
	echo unimplemented
	exit 1

.PHONY: clusterpool/delete-cluster-pool
clusterpool/delete-cluster-pool:
	echo unimplemented
	exit 1

.PHONY: clusterpool/list-cluster-pools
clusterpool/list-cluster-pools:
	echo unimplemented
	exit 1

.PHONY: clusterpool/create-aws-creds
## Requires various credentials env vars specific to this cloud platform
clusterpool/create-aws-creds:
	echo unimplemented
	exit 1

.PHONY: clusterpool/create-azure-creds
## Requires various credentials env vars specific to this cloud platform
clusterpool/create-azure-creds:
	echo unimplemented
	exit 1

.PHONY: clusterpool/create-gcp-creds
## Requires various credentials env vars specific to this cloud platform
clusterpool/create-gcp-creds:
	echo unimplemented
	exit 1

.PHONY: clusterpool/delete-creds
## Takes in a CREDS_SECRET_NAME variable
clusterpool/delete-creds:
	echo unimplemented
	exit 1

.PHONY: clusterpool/create-claim
## Takes in a CLUSTERPOOL variable - the name of the clusterpool to create a claim on
clusterpool/create-claim:
	echo unimplemented
	exit 1

.PHONY: clusterpool/verify-claim
## Takes in a CLUSTER_CLAIM variable - the name of the claim to validate - and validates that the claim was fulfilled
clusterpool/verify-claim:
	echo unimplemented
	exit 1

.PHONY: clusterpool/delete-claim
## Takes in a CLUSTER_ClAIM variable - the name of the claim to delete
clusterpool/delete-claim:
	echo unimplemented
	exit 1

.PHONY: clusetrpool/checkout
## takes in a CLUSTER_ClAIM variable - the name of the claim to create
clusetrpool/checkout:
	echo unimplemented
	exit 1

.PHONY: clusterpool/checkin
## Takes in a CLUSTER_ClAIM variable - the name of the claim to delete
clusterpool/checkin:
	echo unimplemented
	exit 1

.PHONY: clusterpool/get-cluster-kubeconfig
## Takes in a CLUSTER_ClAIM variable - the name of the claim to get creds from
clusterpool/get-cluster-kubeconfig:
	echo unimplemented
	exit 1

.PHONY: clusterpool/get-cluster-credentials
## takes in a CLUSTER_ClAIM variable - the name of the claim to get creds from
clusterpool/get-cluster-credentials:
	echo unimplemented
	exit 1

.PHONY: clusterpool/get-cluster-api
## takes in a CLUSTER_ClAIM variable - the name of the claim to get creds from
clusterpool/get-cluster-api:
	echo unimplemented
	exit 1

.PHONY: clusterpool/get-cluster-console
## takes in a CLUSTER_ClAIM variable - the name of the claim to get creds from
clusterpool/get-cluster-console:
	echo unimplemented
	exit 1

.PHONY: clusterpool/get-cluster-metadata
## takes in a CLUSTER_CLAIM variable and a METADATA_FILE where it will dump the json cluster details - this will consume the previous focused creds
clusterpool/get-cluster-metadata:
	echo unimplemented
	exit 1

